# Getting started with Python programming for Data science

Set up your Python environment
 * Install python
 * Install Anaconda IDE or setup jupyter Notebook
 
Note: Basic knowledge of python operations, variable and datatypes are pre-requisite to this

# Let's Begin!!

Import Package

In [20]:
import numpy as np

In [11]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [12]:
arr = [4,56,2,'My name is',3,7,'Formless']

In [13]:
arr

[4, 56, 2, 'My name is', 3, 7, 'Formless']

### Basic Operations

In [24]:
a = np.array([1,2,4])
a + 5

array([6, 7, 9])

In [28]:
a-2


array([-1,  0,  2])

In [27]:
a/2

array([0.5, 1. , 2. ])

### Array Multiplication

In [29]:
b = np. array([4,2,5])
a*b

array([ 4,  4, 20])

### Matrix Multiplication

In [43]:
c = np.ones((3,3))
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

This is a array multiplication where multiplication is done element with element

In [45]:
c* c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

For the linear algebra matrix multiplication, Numpy has a function dot for matrix multiplication. 

In [44]:
c.dot(c)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

Import packages in python

## Comparision Operation

In [46]:
a

array([1, 2, 4])

In [47]:
b

array([4, 2, 5])

In [48]:
a == b

array([False,  True, False])

## Computing Sum,Min,Max

In [53]:
a


array([1, 2, 4])

In [54]:
np.sum(a)

7

In [55]:
np.min(a)

1

In [56]:
np.max(a)

4

To find min(argmin()) and max(argmax()) index/position number inside array 

In [58]:
np.argmin(a)

0

In [60]:
np.argmax(a)

2

## satatistical Computation

In [64]:
print(a)
np.mean(a)

[1 2 4]


2.3333333333333335

In [65]:
np.std(a)

1.247219128924647

## Flattening and Reshaping of array

In [93]:
d = np.array([[7,4,0],[1,-5,8]])
d

array([[ 7,  4,  0],
       [ 1, -5,  8]])

In [94]:
e = np.ravel(d)
print(e)

[ 7  4  0  1 -5  8]


In [95]:
f =e.reshape((3,2))
f

array([[ 7,  4],
       [ 0,  1],
       [-5,  8]])

## Sorting

In [96]:
d

array([[ 7,  4,  0],
       [ 1, -5,  8]])

In [97]:
np.sort(d)

array([[ 0,  4,  7],
       [-5,  1,  8]])

In [98]:
np.sort(d,axis=0)

array([[ 1, -5,  0],
       [ 7,  4,  8]])

In [99]:
np.sort(d,axis=1)

array([[ 0,  4,  7],
       [-5,  1,  8]])